[package]
name = "configo"
version = "1.0.1"
edition = "2024"

[dependencies]
serde = {version = "*", features = ["derive"]}
serde_yml = {version = "*"}

tokio = {version = "*", features = ["full"]}

log = {version = "*"}
colored = {version = "*"}
